#!/usr/bin/env bash

set -eu

ATTEMPTS=0 # 0 is infinity
COMMAND=()

while [[ "$#" -gt 0 ]]; do
  case "$1" in
  -t | --tries)
    ATTEMPTS="$2"
    shift 2
    ;;
  *)
    COMMAND+=("$1")
    shift
    ;;
  esac
done

main() {
  local attempt=0
  while [[ ATTEMPTS -eq 0 || attempt -lt ATTEMPTS ]]; do
    if "${COMMAND[@]}"; then
      echo "Command succeeded on attempt $((attempt + 1))"
      exit 0
    fi

    ((++attempt))

  done

  echo "Command failed after $attempt attempts"
  exit 1
}

main "$@"
